[build]
  base    = "client"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  included_files = ["../netlify/functions/**"]

[[redirects]]
  from   = "/api/refine"
  to     = "/.netlify/functions/api/refine"
  status = 200

[[redirects]]
  from   = "/api/export"
  to     = "/.netlify/functions/api/export"
  status = 200

[[redirects]]
  from   = "/api/upload"
  to     = "/.netlify/functions/api/upload"
  status = 200

[[redirects]]
  from   = "/api/upload-context"
  to     = "/.netlify/functions/api/upload-context"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
